#pragma once

// map group ids
// `newgroup` indexes are for:
// - MapGroupPointers (see data/maps/maps.asm)
// - MapGroupRoofs (see data/maps/roofs.asm)
// - OutdoorSprites (see data/maps/outdoor_sprites.asm)
// - RoofPals (see gfx/tilesets/roofs.pal)
// `map_const` indexes are for the sub-tables of MapGroupPointers (see data/maps/maps.asm)
// Each map also has associated data:
// - attributes (see data/maps/attributes.asm)
// - blocks (see data/maps/blocks.asm)
// - scripts and events (see data/maps/scripts.asm)

typedef enum {
    MAPGROUP_N_A,
    MAPGROUP_OLIVINE,
    MAPGROUP_MAHOGANY,
    MAPGROUP_DUNGEONS,
    MAPGROUP_ECRUTEAK,
    MAPGROUP_BLACKTHORN,
    MAPGROUP_CINNABAR,
    MAPGROUP_CERULEAN,
    MAPGROUP_AZALEA,
    MAPGROUP_LAKE_OF_RAGE,
    MAPGROUP_VIOLET,
    MAPGROUP_GOLDENROD,
    MAPGROUP_VERMILION,
    MAPGROUP_PALLET,
    MAPGROUP_PEWTER,
    MAPGROUP_FAST_SHIP,
    MAPGROUP_INDIGO,
    MAPGROUP_FUCHSIA,
    MAPGROUP_LAVENDER,
    MAPGROUP_SILVER,
    MAPGROUP_CABLE_CLUB,
    MAPGROUP_CELADON,
    MAPGROUP_CIANWOOD,
    MAPGROUP_VIRIDIAN,
    MAPGROUP_NEW_BARK,
    MAPGROUP_SAFFRON,
    MAPGROUP_CHERRYGROVE
} MapGroup;


#define NUM_MAP_GROUPS MAPGROUP_CHERRYGROVE

typedef struct {
    int width;
    int height;
    MapGroup group;
} Map;

//MAPGROUP_NULL

Map N_A = { 0, 0, MAPGROUP_N_A };

//MAPGROUP_OLIVINE

Map OLIVINE_POKECENTER_1F = { 5, 4, MAPGROUP_OLIVINE };
Map OLIVINE_GYM = { 5, 8, MAPGROUP_OLIVINE };
Map OLIVINE_TIMS_HOUSE = { 4, 4, MAPGROUP_OLIVINE };
Map OLIVINE_HOUSE_BETA = { 4, 4, MAPGROUP_OLIVINE };
Map OLIVINE_PUNISHMENT_SPEECH_HOUSE = { 4, 4, MAPGROUP_OLIVINE };
Map OLIVINE_GOOD_ROD_HOUSE = { 4, 4, MAPGROUP_OLIVINE };
Map OLIVINE_CAFE = { 4, 4, MAPGROUP_OLIVINE };
Map OLIVINE_MART = { 6, 4, MAPGROUP_OLIVINE };
Map ROUTE_38_ECRUTEAK_GATE = { 5, 4, MAPGROUP_OLIVINE };
Map ROUTE_39_BARN = { 4, 4, MAPGROUP_OLIVINE };
Map ROUTE_39_FARMHOUSE = { 4, 4, MAPGROUP_OLIVINE };
Map ROUTE_38 = { 20, 9, MAPGROUP_OLIVINE };
Map ROUTE_39 = { 10, 18, MAPGROUP_OLIVINE };
Map OLIVINE_CITY = { 20, 18, MAPGROUP_OLIVINE };

//MAPGROUP_MAHOGANY

Map MAHOGANY_RED_GYARADOS_SPEECH_HOUSE = { 4, 4, MAPGROUP_MAHOGANY };
Map MAHOGANY_GYM = { 5, 9, MAPGROUP_MAHOGANY };
Map MAHOGANY_POKECENTER_1F = { 5, 4, MAPGROUP_MAHOGANY };
Map ROUTE_42_ECRUTEAK_GATE = { 5, 4, MAPGROUP_MAHOGANY };
Map ROUTE_42 = { 30, 9, MAPGROUP_MAHOGANY };
Map ROUTE_44 = { 30, 9, MAPGROUP_MAHOGANY };
Map MAHOGANY_TOWN = { 10, 9, MAPGROUP_MAHOGANY };

//MAPGROUP_DUNGEONS

Map SPROUT_TOWER_1F = { 10, 8, MAPGROUP_DUNGEONS };
Map SPROUT_TOWER_2F = { 10, 8, MAPGROUP_DUNGEONS };
Map SPROUT_TOWER_3F = { 10, 8, MAPGROUP_DUNGEONS };
Map TIN_TOWER_1F = { 10, 9, MAPGROUP_DUNGEONS };
Map TIN_TOWER_2F = { 10, 9, MAPGROUP_DUNGEONS };
Map TIN_TOWER_3F = { 10, 9, MAPGROUP_DUNGEONS };
Map TIN_TOWER_4F = { 10, 9, MAPGROUP_DUNGEONS };
Map TIN_TOWER_5F = { 10, 9, MAPGROUP_DUNGEONS };
Map TIN_TOWER_6F = { 10, 9, MAPGROUP_DUNGEONS };
Map TIN_TOWER_7F = { 10, 9, MAPGROUP_DUNGEONS };
Map TIN_TOWER_8F = { 10, 9, MAPGROUP_DUNGEONS };
Map TIN_TOWER_9F = { 10, 9, MAPGROUP_DUNGEONS };
Map BURNED_TOWER_1F = { 10, 9, MAPGROUP_DUNGEONS };
Map BURNED_TOWER_B1F = { 10, 9, MAPGROUP_DUNGEONS };
Map NATIONAL_PARK = { 20, 27, MAPGROUP_DUNGEONS };
Map NATIONAL_PARK_BUG_CONTEST = { 20, 27, MAPGROUP_DUNGEONS };
Map RADIO_TOWER_1F = { 9, 4, MAPGROUP_DUNGEONS };
Map RADIO_TOWER_2F = { 9, 4, MAPGROUP_DUNGEONS };
Map RADIO_TOWER_3F = { 9, 4, MAPGROUP_DUNGEONS };
Map RADIO_TOWER_4F = { 9, 4, MAPGROUP_DUNGEONS };
Map RADIO_TOWER_5F = { 9, 4, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_OUTSIDE = { 10, 18, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_HO_OH_CHAMBER = { 4, 5, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_KABUTO_CHAMBER = { 4, 5, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_OMANYTE_CHAMBER = { 4, 5, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_AERODACTYL_CHAMBER = { 4, 5, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_INNER_CHAMBER = { 10, 14, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_RESEARCH_CENTER = { 4, 4, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_HO_OH_ITEM_ROOM = { 4, 5, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_KABUTO_ITEM_ROOM = { 4, 5, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_OMANYTE_ITEM_ROOM = { 4, 5, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM = { 4, 5, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_HO_OH_WORD_ROOM = { 10, 12, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_KABUTO_WORD_ROOM = { 10, 7, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_OMANYTE_WORD_ROOM = { 10, 8, MAPGROUP_DUNGEONS };
Map RUINS_OF_ALPH_AERODACTYL_WORD_ROOM = { 10, 7, MAPGROUP_DUNGEONS };
Map UNION_CAVE_1F = { 10, 18, MAPGROUP_DUNGEONS };
Map UNION_CAVE_B1F = { 10, 18, MAPGROUP_DUNGEONS };
Map UNION_CAVE_B2F = { 10, 18, MAPGROUP_DUNGEONS };
Map SLOWPOKE_WELL_B1F = { 10, 9, MAPGROUP_DUNGEONS };
Map SLOWPOKE_WELL_B2F = { 10, 9, MAPGROUP_DUNGEONS };
Map OLIVINE_LIGHTHOUSE_1F = { 10, 9, MAPGROUP_DUNGEONS };
Map OLIVINE_LIGHTHOUSE_2F = { 10, 9, MAPGROUP_DUNGEONS };
Map OLIVINE_LIGHTHOUSE_3F = { 10, 9, MAPGROUP_DUNGEONS };
Map OLIVINE_LIGHTHOUSE_4F = { 10, 9, MAPGROUP_DUNGEONS };
Map OLIVINE_LIGHTHOUSE_5F = { 10, 9, MAPGROUP_DUNGEONS };
Map OLIVINE_LIGHTHOUSE_6F = { 10, 9, MAPGROUP_DUNGEONS };
Map MAHOGANY_MART_1F = { 4, 4, MAPGROUP_DUNGEONS };
Map TEAM_ROCKET_BASE_B1F = { 15, 9, MAPGROUP_DUNGEONS };
Map TEAM_ROCKET_BASE_B2F = { 15, 9, MAPGROUP_DUNGEONS };
Map TEAM_ROCKET_BASE_B3F = { 15, 9, MAPGROUP_DUNGEONS };
Map ILEX_FOREST = { 15, 27, MAPGROUP_DUNGEONS };
Map GOLDENROD_UNDERGROUND = { 15, 18, MAPGROUP_DUNGEONS };
Map GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES = { 15, 18, MAPGROUP_DUNGEONS };
Map GOLDENROD_DEPT_STORE_B1F = { 10, 9, MAPGROUP_DUNGEONS };
Map GOLDENROD_UNDERGROUND_WAREHOUSE = { 10, 9, MAPGROUP_DUNGEONS };
Map MOUNT_MORTAR_1F_OUTSIDE = { 20, 18, MAPGROUP_DUNGEONS };
Map MOUNT_MORTAR_1F_INSIDE = { 20, 27, MAPGROUP_DUNGEONS };
Map MOUNT_MORTAR_2F_INSIDE = { 20, 18, MAPGROUP_DUNGEONS };
Map MOUNT_MORTAR_B1F = { 20, 18, MAPGROUP_DUNGEONS };
Map ICE_PATH_1F = { 20, 18, MAPGROUP_DUNGEONS };
Map ICE_PATH_B1F = { 10, 18, MAPGROUP_DUNGEONS };
Map ICE_PATH_B2F_MAHOGANY_SIDE = { 10, 9, MAPGROUP_DUNGEONS };
Map ICE_PATH_B2F_BLACKTHORN_SIDE = { 5, 9, MAPGROUP_DUNGEONS };
Map ICE_PATH_B3F = { 10, 9, MAPGROUP_DUNGEONS };
Map WHIRL_ISLAND_NW = { 5, 9, MAPGROUP_DUNGEONS };
Map WHIRL_ISLAND_NE = { 10, 9, MAPGROUP_DUNGEONS };
Map WHIRL_ISLAND_SW = { 10, 9, MAPGROUP_DUNGEONS };
Map WHIRL_ISLAND_CAVE = { 5, 9, MAPGROUP_DUNGEONS };
Map WHIRL_ISLAND_SE = { 5, 9, MAPGROUP_DUNGEONS };
Map WHIRL_ISLAND_B1F = { 20, 18, MAPGROUP_DUNGEONS };
Map WHIRL_ISLAND_B2F = { 10, 18, MAPGROUP_DUNGEONS };
Map WHIRL_ISLAND_LUGIA_CHAMBER = { 10, 9, MAPGROUP_DUNGEONS };
Map SILVER_CAVE_ROOM_1 = { 10, 18, MAPGROUP_DUNGEONS };
Map SILVER_CAVE_ROOM_2 = { 15, 18, MAPGROUP_DUNGEONS };
Map SILVER_CAVE_ROOM_3 = { 10, 18, MAPGROUP_DUNGEONS };
Map SILVER_CAVE_ITEM_ROOMS = { 10, 9, MAPGROUP_DUNGEONS };
Map DARK_CAVE_VIOLET_ENTRANCE = { 20, 18, MAPGROUP_DUNGEONS };
Map DARK_CAVE_BLACKTHORN_ENTRANCE = { 15, 18, MAPGROUP_DUNGEONS };
Map DRAGONS_DEN_1F = { 5, 9, MAPGROUP_DUNGEONS };
Map DRAGONS_DEN_B1F = { 20, 18, MAPGROUP_DUNGEONS };
Map DRAGON_SHRINE = { 5, 5, MAPGROUP_DUNGEONS };
Map TOHJO_FALLS = { 15, 9, MAPGROUP_DUNGEONS };
Map DIGLETTS_CAVE = { 10, 18, MAPGROUP_DUNGEONS };
Map MOUNT_MOON = { 15, 9, MAPGROUP_DUNGEONS };
Map UNDERGROUND_PATH = { 3, 14, MAPGROUP_DUNGEONS };
Map ROCK_TUNNEL_1F = { 15, 18, MAPGROUP_DUNGEONS };
Map ROCK_TUNNEL_B1F = { 15, 18, MAPGROUP_DUNGEONS };
Map SAFARI_ZONE_FUCHSIA_GATE_BETA = { 5, 4, MAPGROUP_DUNGEONS };
Map SAFARI_ZONE_BETA = { 10, 18, MAPGROUP_DUNGEONS };
Map VICTORY_ROAD = { 10, 36, MAPGROUP_DUNGEONS };

//MAPGROUP_ECRUTEAK

Map ECRUTEAK_TIN_TOWER_ENTRANCE = { 10, 9, MAPGROUP_ECRUTEAK };
Map WISE_TRIOS_ROOM = { 4, 4, MAPGROUP_ECRUTEAK };
Map ECRUTEAK_POKECENTER_1F = { 5, 4, MAPGROUP_ECRUTEAK };
Map ECRUTEAK_LUGIA_SPEECH_HOUSE = { 4, 4, MAPGROUP_ECRUTEAK };
Map DANCE_THEATRE = { 6, 7, MAPGROUP_ECRUTEAK };
Map ECRUTEAK_MART = { 6, 4, MAPGROUP_ECRUTEAK };
Map ECRUTEAK_GYM = { 5, 9, MAPGROUP_ECRUTEAK };
Map ECRUTEAK_ITEMFINDER_HOUSE = { 4, 4, MAPGROUP_ECRUTEAK };
Map ECRUTEAK_CITY = { 20, 18, MAPGROUP_ECRUTEAK };

//MAPGROUP_BLACKTHORN

Map BLACKTHORN_GYM_1F = { 5, 9, MAPGROUP_BLACKTHORN };
Map BLACKTHORN_GYM_2F = { 5, 9, MAPGROUP_BLACKTHORN };
Map BLACKTHORN_DRAGON_SPEECH_HOUSE = { 4, 4, MAPGROUP_BLACKTHORN };
Map BLACKTHORN_EMYS_HOUSE = { 4, 4, MAPGROUP_BLACKTHORN };
Map BLACKTHORN_MART = { 6, 4, MAPGROUP_BLACKTHORN };
Map BLACKTHORN_POKECENTER_1F = { 5, 4, MAPGROUP_BLACKTHORN };
Map MOVE_DELETERS_HOUSE = { 4, 4, MAPGROUP_BLACKTHORN };
Map ROUTE_45 = { 10, 45, MAPGROUP_BLACKTHORN };
Map ROUTE_46 = { 10, 18, MAPGROUP_BLACKTHORN };
Map BLACKTHORN_CITY = { 20, 18, MAPGROUP_BLACKTHORN };

//MAPGROUP_CINNABAR

Map CINNABAR_POKECENTER_1F = { 5, 4, MAPGROUP_CINNABAR };
Map CINNABAR_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_CINNABAR };
Map ROUTE_19_FUCHSIA_GATE = { 5, 4, MAPGROUP_CINNABAR };
Map SEAFOAM_GYM = { 5, 4, MAPGROUP_CINNABAR };
Map ROUTE_19 = { 10, 18, MAPGROUP_CINNABAR };
Map ROUTE_20 = { 30, 9, MAPGROUP_CINNABAR };
Map ROUTE_21 = { 10, 18, MAPGROUP_CINNABAR };
Map CINNABAR_ISLAND = { 10, 9, MAPGROUP_CINNABAR };

//MAPGROUP_CERULEAN

Map CERULEAN_GYM_BADGE_SPEECH_HOUSE = { 4, 4, MAPGROUP_CERULEAN };
Map CERULEAN_POLICE_STATION = { 4, 4, MAPGROUP_CERULEAN };
Map CERULEAN_TRADE_SPEECH_HOUSE = { 4, 4, MAPGROUP_CERULEAN };
Map CERULEAN_POKECENTER_1F = { 5, 4, MAPGROUP_CERULEAN };
Map CERULEAN_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_CERULEAN };
Map CERULEAN_GYM = { 5, 8, MAPGROUP_CERULEAN };
Map CERULEAN_MART = { 6, 4, MAPGROUP_CERULEAN };
Map ROUTE_10_POKECENTER_1F = { 5, 4, MAPGROUP_CERULEAN };
Map ROUTE_10_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_CERULEAN };
Map POWER_PLANT = { 10, 9, MAPGROUP_CERULEAN };
Map BILLS_HOUSE = { 4, 4, MAPGROUP_CERULEAN };
Map ROUTE_4 = { 20, 9, MAPGROUP_CERULEAN };
Map ROUTE_9 = { 30, 9, MAPGROUP_CERULEAN };
Map ROUTE_10_NORTH = { 10, 9, MAPGROUP_CERULEAN };
Map ROUTE_24 = { 10, 9, MAPGROUP_CERULEAN };
Map ROUTE_25 = { 30, 9, MAPGROUP_CERULEAN };
Map CERULEAN_CITY = { 20, 18, MAPGROUP_CERULEAN };

//MAPGROUP_AZALEA

Map AZALEA_POKECENTER_1F = { 5, 4, MAPGROUP_AZALEA };
Map CHARCOAL_KILN = { 4, 4, MAPGROUP_AZALEA };
Map AZALEA_MART = { 6, 4, MAPGROUP_AZALEA };
Map KURTS_HOUSE = { 8, 4, MAPGROUP_AZALEA };
Map AZALEA_GYM = { 5, 8, MAPGROUP_AZALEA };
Map ROUTE_33 = { 10, 9, MAPGROUP_AZALEA };
Map AZALEA_TOWN = { 20, 9, MAPGROUP_AZALEA };

//MAPGROUP_LAKE_OF_RAGE

Map LAKE_OF_RAGE_HIDDEN_POWER_HOUSE = { 4, 4, MAPGROUP_LAKE_OF_RAGE };
Map LAKE_OF_RAGE_MAGIKARP_HOUSE = { 4, 4, MAPGROUP_LAKE_OF_RAGE };
Map ROUTE_43_MAHOGANY_GATE = { 5, 4, MAPGROUP_LAKE_OF_RAGE };
Map ROUTE_43_GATE = { 5, 4, MAPGROUP_LAKE_OF_RAGE };
Map ROUTE_43 = { 10, 27, MAPGROUP_LAKE_OF_RAGE };
Map LAKE_OF_RAGE = { 20, 18, MAPGROUP_LAKE_OF_RAGE };

//MAPGROUP_VIOLET

Map ROUTE_32 = { 10, 45, MAPGROUP_VIOLET };
Map ROUTE_35 = { 10, 18, MAPGROUP_VIOLET };
Map ROUTE_36 = { 30, 9,  MAPGROUP_VIOLET };
Map ROUTE_37 = { 10, 9,  MAPGROUP_VIOLET };
Map VIOLET_CITY = { 20, 18, MAPGROUP_VIOLET };
Map VIOLET_MART = { 6, 4, MAPGROUP_VIOLET };
Map VIOLET_GYM = { 5, 8, MAPGROUP_VIOLET };
Map EARLS_POKEMON_ACADEMY = { 4, 8, MAPGROUP_VIOLET };
Map VIOLET_NICKNAME_SPEECH_HOUSE = { 4, 4, MAPGROUP_VIOLET };
Map VIOLET_POKECENTER_1F = { 5, 4, MAPGROUP_VIOLET };
Map VIOLET_KYLES_HOUSE = { 4, 4, MAPGROUP_VIOLET };
Map ROUTE_32_RUINS_OF_ALPH_GATE = { 5, 4, MAPGROUP_VIOLET };
Map ROUTE_32_POKECENTER_1F = { 5, 4, MAPGROUP_VIOLET };
Map ROUTE_35_GOLDENROD_GATE = { 5, 4, MAPGROUP_VIOLET };
Map ROUTE_35_NATIONAL_PARK_GATE = { 4, 4, MAPGROUP_VIOLET };
Map ROUTE_36_RUINS_OF_ALPH_GATE = { 5, 4, MAPGROUP_VIOLET };
Map ROUTE_36_NATIONAL_PARK_GATE = { 5, 4, MAPGROUP_VIOLET };

//MAPGROUP_GOLDENROD

Map ROUTE_34 = { 10, 27, MAPGROUP_GOLDENROD };
Map GOLDENROD_CITY = { 20, 18, MAPGROUP_GOLDENROD };
Map GOLDENROD_GYM = { 10, 9, MAPGROUP_GOLDENROD };
Map GOLDENROD_BIKE_SHOP = { 4, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_HAPPINESS_RATER = { 4, 4, MAPGROUP_GOLDENROD };
Map BILLS_FAMILYS_HOUSE = { 4, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_MAGNET_TRAIN_STATION = { 10, 9, MAPGROUP_GOLDENROD };
Map GOLDENROD_FLOWER_SHOP = { 4, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_PP_SPEECH_HOUSE = { 4, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_NAME_RATER = { 4, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_DEPT_STORE_1F = { 8, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_DEPT_STORE_2F = { 8, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_DEPT_STORE_3F = { 8, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_DEPT_STORE_4F = { 8, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_DEPT_STORE_5F = { 8, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_DEPT_STORE_6F = { 8, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_DEPT_STORE_ELEVATOR = { 2, 2, MAPGROUP_GOLDENROD };
Map GOLDENROD_DEPT_STORE_ROOF = { 8, 4, MAPGROUP_GOLDENROD };
Map GOLDENROD_GAME_CORNER = { 10, 7, MAPGROUP_GOLDENROD };
Map GOLDENROD_POKECENTER_1F = { 5, 4, MAPGROUP_GOLDENROD };
Map POKECOM_CENTER_ADMIN_OFFICE_MOBILE = { 16, 16, MAPGROUP_GOLDENROD };
Map ILEX_FOREST_AZALEA_GATE = { 5, 4, MAPGROUP_GOLDENROD };
Map ROUTE_34_ILEX_FOREST_GATE = { 5, 4, MAPGROUP_GOLDENROD };
Map DAY_CARE = { 5, 4, MAPGROUP_GOLDENROD };

//MAPGROUP_VERMILION

Map ROUTE_6 = { 10, 9, MAPGROUP_VERMILION };
Map ROUTE_11 = { 20, 9, MAPGROUP_VERMILION };
Map VERMILION_CITY = { 20, 18, MAPGROUP_VERMILION };
Map VERMILION_FISHING_SPEECH_HOUSE = { 4, 4, MAPGROUP_VERMILION };
Map VERMILION_POKECENTER_1F = { 5, 4, MAPGROUP_VERMILION };
Map VERMILION_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_VERMILION };
Map POKEMON_FAN_CLUB = { 5, 4, MAPGROUP_VERMILION };
Map VERMILION_MAGNET_TRAIN_SPEECH_HOUSE = { 4, 4, MAPGROUP_VERMILION };
Map VERMILION_MART = { 6, 4, MAPGROUP_VERMILION };
Map VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE = { 4, 4, MAPGROUP_VERMILION };
Map VERMILION_GYM = { 5, 9, MAPGROUP_VERMILION };
Map ROUTE_6_SAFFRON_GATE = { 5, 4, MAPGROUP_VERMILION };
Map ROUTE_6_UNDERGROUND_PATH_ENTRANCE = { 4, 4, MAPGROUP_VERMILION };

//MAPGROUP_PALLET

Map ROUTE_1 = { 10, 18, MAPGROUP_PALLET };
Map PALLET_TOWN = { 10, 9, MAPGROUP_PALLET };
Map REDS_HOUSE_1F = { 4, 4, MAPGROUP_PALLET };
Map REDS_HOUSE_2F = { 4, 4, MAPGROUP_PALLET };
Map BLUES_HOUSE = { 4, 4, MAPGROUP_PALLET };
Map OAKS_LAB = { 5, 6, MAPGROUP_PALLET };

//MAPGROUP_PEWTER

Map ROUTE_3 = { 30, 9, MAPGROUP_PEWTER };
Map PEWTER_CITY = { 20, 18, MAPGROUP_PEWTER };
Map PEWTER_NIDORAN_SPEECH_HOUSE = { 4, 4, MAPGROUP_PEWTER };
Map PEWTER_GYM = { 5, 7, MAPGROUP_PEWTER };
Map PEWTER_MART = { 6, 4, MAPGROUP_PEWTER };
Map PEWTER_POKECENTER_1F = { 5, 4, MAPGROUP_PEWTER };
Map PEWTER_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_PEWTER };
Map PEWTER_SNOOZE_SPEECH_HOUSE = { 4, 4, MAPGROUP_PEWTER };

//MAPGROUP_FAST_SHIP

Map OLIVINE_PORT = { 10, 18, MAPGROUP_FAST_SHIP };
Map VERMILION_PORT = { 10, 18, MAPGROUP_FAST_SHIP };
Map FAST_SHIP_1F = { 16, 9, MAPGROUP_FAST_SHIP };
Map FAST_SHIP_CABINS_NNW_NNE_NE = { 4, 16, MAPGROUP_FAST_SHIP };
Map FAST_SHIP_CABINS_SW_SSW_NW = { 4, 16, MAPGROUP_FAST_SHIP };
Map FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN = { 5, 17, MAPGROUP_FAST_SHIP };
Map FAST_SHIP_B1F = { 16, 8, MAPGROUP_FAST_SHIP };
Map OLIVINE_PORT_PASSAGE = { 10, 9, MAPGROUP_FAST_SHIP };
Map VERMILION_PORT_PASSAGE = { 10, 9, MAPGROUP_FAST_SHIP };
Map MOUNT_MOON_SQUARE = { 15, 9, MAPGROUP_FAST_SHIP };
Map MOUNT_MOON_GIFT_SHOP = { 4, 4, MAPGROUP_FAST_SHIP };
Map TIN_TOWER_ROOF = { 10, 9, MAPGROUP_FAST_SHIP };

//MAPGROUP_INDIGO

Map ROUTE_23 = { 10, 9, MAPGROUP_INDIGO };
Map INDIGO_PLATEAU_POKECENTER_1F = { 9, 7, MAPGROUP_INDIGO };
Map WILLS_ROOM = { 5, 9, MAPGROUP_INDIGO };
Map KOGAS_ROOM = { 5, 9, MAPGROUP_INDIGO };
Map BRUNOS_ROOM = { 5, 9, MAPGROUP_INDIGO };
Map KARENS_ROOM = { 5, 9, MAPGROUP_INDIGO };
Map LANCES_ROOM = { 5, 12, MAPGROUP_INDIGO };
Map HALL_OF_FAME = { 5, 7, MAPGROUP_INDIGO };

// MAPGROUP_FUCHSIA

Map ROUTE_13 = { 30, 9, MAPGROUP_FUCHSIA };
Map ROUTE_14 = { 10, 18, MAPGROUP_FUCHSIA };
Map ROUTE_15 = { 20, 9, MAPGROUP_FUCHSIA };
Map ROUTE_18 = { 10, 9, MAPGROUP_FUCHSIA };
Map FUCHSIA_CITY = { 20, 18, MAPGROUP_FUCHSIA };
Map FUCHSIA_MART = { 6, 4, MAPGROUP_FUCHSIA };
Map SAFARI_ZONE_MAIN_OFFICE = { 4, 4, MAPGROUP_FUCHSIA };
Map FUCHSIA_GYM = { 5, 9, MAPGROUP_FUCHSIA };
Map BILLS_BROTHERS_HOUSE = { 4, 4, MAPGROUP_FUCHSIA };
Map FUCHSIA_POKECENTER_1F = { 5, 4, MAPGROUP_FUCHSIA };
Map FUCHSIA_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_FUCHSIA };
Map SAFARI_ZONE_WARDENS_HOME = { 5, 4, MAPGROUP_FUCHSIA };
Map ROUTE_15_FUCHSIA_GATE = { 5, 4, MAPGROUP_FUCHSIA };

// MAPGROUP_LAVENDER

Map ROUTE_8 = { 20, 9, MAPGROUP_LAVENDER };
Map ROUTE_12 = { 10, 27, MAPGROUP_LAVENDER };
Map ROUTE_10_SOUTH = { 10, 9, MAPGROUP_LAVENDER };
Map LAVENDER_TOWN = { 10, 9, MAPGROUP_LAVENDER };
Map LAVENDER_POKECENTER_1F = { 5, 4, MAPGROUP_LAVENDER };
Map LAVENDER_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_LAVENDER };
Map MR_FUJIS_HOUSE = { 5, 4, MAPGROUP_LAVENDER };
Map LAVENDER_SPEECH_HOUSE = { 4, 4, MAPGROUP_LAVENDER };
Map LAVENDER_NAME_RATER = { 4, 4, MAPGROUP_LAVENDER };
Map LAVENDER_MART = { 6, 4, MAPGROUP_LAVENDER };
Map SOUL_HOUSE = { 5, 4, MAPGROUP_LAVENDER };
Map LAV_RADIO_TOWER_1F = { 10, 4, MAPGROUP_LAVENDER };
Map ROUTE_8_SAFFRON_GATE = { 5, 4, MAPGROUP_LAVENDER };
Map ROUTE_12_SUPER_ROD_HOUSE = { 4, 4, MAPGROUP_LAVENDER };

//MAPGROUP_SILVER

// MAPGROUP_SILVER

Map ROUTE_28 = { 20, 9, MAPGROUP_SILVER };
Map SILVER_CAVE_OUTSIDE = { 20, 18, MAPGROUP_SILVER };
Map SILVER_CAVE_POKECENTER_1F = { 5, 4, MAPGROUP_SILVER };
Map ROUTE_28_STEEL_WING_HOUSE = { 4, 4, MAPGROUP_SILVER };

// MAPGROUP_CABLE_CLUB

Map POKECENTER_2F = { 8, 4, MAPGROUP_CABLE_CLUB };
Map TRADE_CENTER = { 5, 4, MAPGROUP_CABLE_CLUB };
Map COLOSSEUM = { 5, 4, MAPGROUP_CABLE_CLUB };
Map TIME_CAPSULE = { 5, 4, MAPGROUP_CABLE_CLUB };
Map MOBILE_TRADE_ROOM = { 5, 4, MAPGROUP_CABLE_CLUB };
Map MOBILE_BATTLE_ROOM = { 5, 4, MAPGROUP_CABLE_CLUB };

//MAPGROUP_CELADON

Map ROUTE_7 = { 10, 9, MAPGROUP_CELADON };
Map ROUTE_16 = { 10, 9, MAPGROUP_CELADON };
Map ROUTE_17 = { 10, 45, MAPGROUP_CELADON };
Map CELADON_CITY = { 20, 18, MAPGROUP_CELADON };
Map CELADON_DEPT_STORE_1F = { 8, 4, MAPGROUP_CELADON };
Map CELADON_DEPT_STORE_2F = { 8, 4, MAPGROUP_CELADON };
Map CELADON_DEPT_STORE_3F = { 8, 4, MAPGROUP_CELADON };
Map CELADON_DEPT_STORE_4F = { 8, 4, MAPGROUP_CELADON };
Map CELADON_DEPT_STORE_5F = { 8, 4, MAPGROUP_CELADON };
Map CELADON_DEPT_STORE_6F = { 8, 4, MAPGROUP_CELADON };
Map CELADON_DEPT_STORE_ELEVATOR = { 2, 2, MAPGROUP_CELADON };
Map CELADON_MANSION_1F = { 4, 5, MAPGROUP_CELADON };
Map CELADON_MANSION_2F = { 4, 5, MAPGROUP_CELADON };
Map CELADON_MANSION_3F = { 4, 5, MAPGROUP_CELADON };
Map CELADON_MANSION_ROOF = { 4, 5, MAPGROUP_CELADON };
Map CELADON_MANSION_ROOF_HOUSE = { 4, 4, MAPGROUP_CELADON };
Map CELADON_POKECENTER_1F = { 5, 4, MAPGROUP_CELADON };
Map CELADON_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_CELADON };
Map CELADON_GAME_CORNER = { 10, 7, MAPGROUP_CELADON };
Map CELADON_GAME_CORNER_PRIZE_ROOM = { 3, 3, MAPGROUP_CELADON };
Map CELADON_GYM = { 5, 9, MAPGROUP_CELADON };
Map CELADON_CAFE = { 6, 4, MAPGROUP_CELADON };
Map ROUTE_16_FUCHSIA_SPEECH_HOUSE = { 4, 4, MAPGROUP_CELADON };
Map ROUTE_16_GATE = { 5, 4, MAPGROUP_CELADON };
Map ROUTE_7_SAFFRON_GATE = { 5, 4, MAPGROUP_CELADON };
Map ROUTE_17_ROUTE_18_GATE = { 5, 4, MAPGROUP_CELADON };

// MAPGROUP_CIANWOOD

Map ROUTE_40 = { 10, 18, MAPGROUP_CIANWOOD };
Map ROUTE_41 = { 25, 27, MAPGROUP_CIANWOOD };
Map CIANWOOD_CITY = { 15, 27, MAPGROUP_CIANWOOD };
Map MANIAS_HOUSE = { 4, 4, MAPGROUP_CIANWOOD };
Map CIANWOOD_GYM = { 5, 9, MAPGROUP_CIANWOOD };
Map CIANWOOD_POKECENTER_1F = { 5, 4, MAPGROUP_CIANWOOD };
Map CIANWOOD_PHARMACY = { 4, 4, MAPGROUP_CIANWOOD };
Map CIANWOOD_PHOTO_STUDIO = { 4, 4, MAPGROUP_CIANWOOD };
Map CIANWOOD_LUGIA_SPEECH_HOUSE = { 4, 4, MAPGROUP_CIANWOOD };
Map POKE_SEERS_HOUSE = { 4, 4, MAPGROUP_CIANWOOD };
Map BATTLE_TOWER_1F = { 8, 5, MAPGROUP_CIANWOOD };
Map BATTLE_TOWER_BATTLE_ROOM = { 4, 4, MAPGROUP_CIANWOOD };
Map BATTLE_TOWER_ELEVATOR = { 2, 2, MAPGROUP_CIANWOOD };
Map BATTLE_TOWER_HALLWAY = { 11, 2, MAPGROUP_CIANWOOD };
Map ROUTE_40_BATTLE_TOWER_GATE = { 5, 4, MAPGROUP_CIANWOOD };
Map BATTLE_TOWER_OUTSIDE = { 10, 14, MAPGROUP_CIANWOOD };

//MAPGROUP_VIRIDIAN

Map ROUTE_2 = { 10, 27, MAPGROUP_VIRIDIAN };
Map ROUTE_22 = { 20, 9, MAPGROUP_VIRIDIAN };
Map VIRIDIAN_CITY = { 20, 18, MAPGROUP_VIRIDIAN };
Map VIRIDIAN_GYM = { 5, 9, MAPGROUP_VIRIDIAN };
Map VIRIDIAN_NICKNAME_SPEECH_HOUSE = { 4, 4, MAPGROUP_VIRIDIAN };
Map TRAINER_HOUSE_1F = { 5, 7, MAPGROUP_VIRIDIAN };
Map TRAINER_HOUSE_B1F = { 5, 8, MAPGROUP_VIRIDIAN };
Map VIRIDIAN_MART = { 6, 4, MAPGROUP_VIRIDIAN };
Map VIRIDIAN_POKECENTER_1F = { 5, 4, MAPGROUP_VIRIDIAN };
Map VIRIDIAN_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_VIRIDIAN };
Map ROUTE_2_NUGGET_HOUSE = { 4, 4, MAPGROUP_VIRIDIAN };
Map ROUTE_2_GATE = { 5, 4, MAPGROUP_VIRIDIAN };
Map VICTORY_ROAD_GATE = { 10, 9, MAPGROUP_VIRIDIAN };

//MAPGROUP_NEW_BARK

Map ROUTE_26 = { 10, 54, MAPGROUP_NEW_BARK };
Map ROUTE_27 = { 40, 9, MAPGROUP_NEW_BARK };
Map ROUTE_29 = { 30, 9, MAPGROUP_NEW_BARK };
Map NEW_BARK_TOWN = { 10, 9, MAPGROUP_NEW_BARK };
Map ELMS_LAB = { 5, 6, MAPGROUP_NEW_BARK };
Map PLAYERS_HOUSE_1F = { 5, 4, MAPGROUP_NEW_BARK };
Map PLAYERS_HOUSE_2F = { 4, 3, MAPGROUP_NEW_BARK };
Map PLAYERS_NEIGHBORS_HOUSE = { 4, 4, MAPGROUP_NEW_BARK };
Map ELMS_HOUSE = { 4, 4, MAPGROUP_NEW_BARK };
Map ROUTE_26_HEAL_HOUSE = { 4, 4, MAPGROUP_NEW_BARK };
Map DAY_OF_WEEK_SIBLINGS_HOUSE = { 4, 4, MAPGROUP_NEW_BARK };
Map ROUTE_27_SANDSTORM_HOUSE = { 4, 4, MAPGROUP_NEW_BARK };
Map ROUTE_29_ROUTE_46_GATE = { 5, 4, MAPGROUP_NEW_BARK };

//MAPGROUP_SAFFRON

Map ROUTE_5 = { 10, 9, MAPGROUP_SAFFRON };
Map SAFFRON_CITY = { 20, 18, MAPGROUP_SAFFRON };
Map FIGHTING_DOJO = { 5, 6, MAPGROUP_SAFFRON };
Map SAFFRON_GYM = { 10, 9, MAPGROUP_SAFFRON };
Map SAFFRON_MART = { 6, 4, MAPGROUP_SAFFRON };
Map SAFFRON_POKECENTER_1F = { 5, 4, MAPGROUP_SAFFRON };
Map SAFFRON_POKECENTER_2F_BETA = { 8, 4, MAPGROUP_SAFFRON };
Map MR_PSYCHICS_HOUSE = { 4, 4, MAPGROUP_SAFFRON };
Map SAFFRON_MAGNET_TRAIN_STATION = { 10, 9, MAPGROUP_SAFFRON };
Map SILPH_CO_1F = { 8, 4, MAPGROUP_SAFFRON };
Map COPYCATS_HOUSE_1F = { 4, 4, MAPGROUP_SAFFRON };
Map COPYCATS_HOUSE_2F = { 5, 3, MAPGROUP_SAFFRON };
Map ROUTE_5_UNDERGROUND_PATH_ENTRANCE = { 4, 4, MAPGROUP_SAFFRON };
Map ROUTE_5_SAFFRON_GATE = { 5, 4, MAPGROUP_SAFFRON };
Map ROUTE_5_CLEANSE_TAG_HOUSE = { 4, 4, MAPGROUP_SAFFRON };

//MAPGROUP_CHERRYGROVE

Map ROUTE_30 = { 10, 27, MAPGROUP_CHERRYGROVE };
Map ROUTE_31 = { 20, 9, MAPGROUP_CHERRYGROVE };
Map CHERRYGROVE_CITY = { 20, 9, MAPGROUP_CHERRYGROVE };
Map CHERRYGROVE_MART = { 6, 4, MAPGROUP_CHERRYGROVE };
Map CHERRYGROVE_POKECENTER_1F = { 5, 4, MAPGROUP_CHERRYGROVE };
Map CHERRYGROVE_GYM_SPEECH_HOUSE = { 4, 4, MAPGROUP_CHERRYGROVE };
Map GUIDE_GENTS_HOUSE = { 4, 4, MAPGROUP_CHERRYGROVE };
Map CHERRYGROVE_EVOLUTION_SPEECH_HOUSE = { 4, 4, MAPGROUP_CHERRYGROVE };
Map ROUTE_30_BERRY_HOUSE = { 4, 4, MAPGROUP_CHERRYGROVE };
Map MR_POKEMONS_HOUSE = { 4, 4, MAPGROUP_CHERRYGROVE };
Map ROUTE_31_VIOLET_GATE = { 5, 4, MAPGROUP_CHERRYGROVE };
