void BetaLoadPlayerTrainerClass(void);
void MovePlayerPicRight(void);
void MovePlayerPicLeft(void);
void MovePlayerPic(void);
void ShowPlayerNamingChoices(void);
void GetPlayerNameArray(void);
void GetPlayerIcon(void);
void GetPlayerIcon_Conv(uint16_t* ptr, uint8_t* bank);
void GetCardPic(void);
void ChrisCardPic(void);
void KrisCardPic(void);
void TrainerCardGFX(void);
void GetPlayerBackpic(void);
void GetChrisBackpic(void);
void HOF_LoadTrainerFrontpic(void);
void DrawIntroPlayerPic(void);
void ChrisPic(void);
void KrisPic(void);
void GetKrisBackpic(void);
void KrisBackpic(void);
//#include "data/player_names.h"
//#include "gfx/trainer_card/chris_card.2bpp"
//#include "gfx/trainer_card/kris_card.2bpp"
//#include "gfx/trainer_card/trainer_card.2bpp"
//#include "gfx/player/chris.2bpp"
//#include "gfx/player/kris.2bpp"
//#include "gfx/player/kris_back.2bpp"
