void ResetMapBufferEventFlags(void);
void ResetBikeFlags(void);
void ResetFlashIfOutOfCave(void);
void EventFlagAction(void);
void EventFlagAction_Conv(uint16_t bit, uint8_t func);
void FlagAction(void);
void FlagAction_Conv(uint16_t flag, uint16_t bit, uint8_t func);
void CheckReceivedDex(void);
void CheckBPressedDebug(void);
void xor_a(void);
void xor_a_dec_a(void);
void CheckFieldDebug(void);
