void UpdatePalsIfCGB(void);
bool UpdatePalsIfCGB_Conv(void);
void UpdateCGBPals(void);
bool UpdateCGBPals_Conv(void);
void ForceUpdateCGBPals(void);
bool ForceUpdateCGBPals_Conv(void);
void DmgToCgbBGPals(void);
void DmgToCgbBGPals_Conv(uint8_t a);
void DmgToCgbObjPals(void);
void DmgToCgbObjPals_Conv(uint8_t d, uint8_t e);
void DmgToCgbObjPal0(void);
void DmgToCgbObjPal1(void);
void CopyPals(void);
void CopyPals_Conv(uint16_t hl, uint16_t de, uint8_t b, uint8_t c);
void ClearVBank1(void);
void ClearVBank1_Conv(void);
void GSReloadPalettes(void);
void ReloadSpritesNoPalettes(void);
void SwapTextboxPalettes(void);
void ScrollBGMapPalettes(void);
