void IsAPokemon(void);
bool IsAPokemon_Conv(uint8_t species);
void DrawBattleHPBar(void);
void PrepMonFrontpic(void);
void v_PrepMonFrontpic(void);
void PlayStereoCry(void);
void PlayStereoCry2(void);
void PlayMonCry(void);
void PlayMonCry2(void);
void v_PlayMonCry(void);
void LoadCry(void);
uint16_t LoadCry_Conv(uint8_t a);
void GetCryIndex(void);
int16_t GetCryIndex_Conv(uint8_t index);
void PrintLevel(void);
void PrintLevel_Force3Digits(void);
void Print8BitNumLeftAlign(void);
void GetNthMove(void);
void GetBaseData(void);
void GetBaseData_Conv(void);
void GetCurNickname(void);
void GetCurNickname_Conv(void);
void GetNickname(void);
void GetNickname_Conv(uint16_t hl, uint8_t a);
