void LoadWildMonData(void);
void FindNest(void);
void TryWildEncounter(void);
void GetMapEncounterRate(void);
void ApplyMusicEffectOnEncounterRate(void);
void ApplyCleanseTagEffectOnEncounterRate(void);
void ChooseWildEncounter(void);
void CheckRepelEffect(void);
void LoadWildMonDataPointer(void);
void v_GrassWildmonLookup(void);
void v_WaterWildmonLookup(void);
void v_JohtoWildmonCheck(void);
void v_SwarmWildmonCheck(void);
void v_NoSwarmWildmon(void);
void v_NormalWildmonOK(void);
void CopyCurrMapDE(void);
void LookUpWildmonsForMapDE(void);
void InitRoamMons(void);
void CheckEncounterRoamMon(void);
void UpdateRoamMons(void);
void JumpRoamMons(void);
void JumpRoamMon(void);
void v_BackUpMapIndices(void);
void ValidateTempWildMonSpecies(void);
void RandomUnseenWildMon(void);
void RandomPhoneWildMon(void);
void RandomPhoneMon(void);
//#include "data/wild/probabilities.h"
//#include "data/wild/roammon_maps.h"
//#include "data/wild/johto_grass.h"
//#include "data/wild/johto_water.h"
//#include "data/wild/kanto_grass.h"
//#include "data/wild/kanto_water.h"
//#include "data/wild/swarm_grass.h"
//#include "data/wild/swarm_water.h"
