void AddPhoneNumber(void);
bool AddPhoneNumber_Conv(uint8_t c);
void DelCellNum(void);
bool DelCellNum_Conv(uint8_t c);
void CheckCellNum(void);
void v_CheckCellNum(void);
uint16_t v_CheckCellNum_Conv(uint8_t c);
void Phone_FindOpenSlot(void);
uint16_t Phone_FindOpenSlot_Conv(uint8_t c);
void GetRemainingSpaceInPhoneList(void);
uint8_t GetRemainingSpaceInPhoneList_Conv(uint8_t c);
void BrokenPlaceFarString(void);
void CheckPhoneCall(void);
void CheckPhoneContactTimeOfDay(void);
void ChooseRandomCaller(void);
void GetAvailableCallers(void);
void CheckSpecialPhoneCall(void);
void SpecialCallOnlyWhenOutside(void);
bool SpecialCallOnlyWhenOutside_Conv(void);
void SpecialCallWhereverYouAre(void);
bool SpecialCallWhereverYouAre_Conv(void);
void MakePhoneCallFromPokegear(void);
void LoadPhoneScriptBank(void);
void LoadOutOfAreaScript(void);
void LoadCallerScript(void);
void WrongNumber(void);
extern const uint8_t Script_ReceivePhoneCall[];
void Script_SpecialBillCall_LoadBillScript(void);
void Script_SpecialElmCall(void);
void RingTwice_StartCall(void);
void PhoneCall(void);
void Phone_NoSignal(void);
void HangUp(void);
void Phone_CallEnd(void);
void HangUp_ShutDown(void);
void HangUp_Beep(void);
void PhoneClickText(void);
void HangUp_BoopOn(void);
void PhoneEllipseText(void);
void HangUp_BoopOff(void);
void Phone_StartRinging(void);
void HangUp_Wait20Frames(void);
void Phone_Wait20Frames(void);
void Phone_TextboxWithName(void);
void Phone_CallerTextbox(void);
void Phone_CallerTextbox_Conv(void);
void GetCallerClassAndName(void);
void CheckCanDeletePhoneNumber(void);
void GetCallerTrainerClass(void);
void GetCallerName(void);
void Phone_GetTrainerName(void);
void Phone_GetTrainerClassName(void);
void GetCallerLocation(void);
void PhoneOutOfAreaScript(void);
void PhoneOutOfAreaText(void);
void PhoneScript_JustTalkToThem(void);
void PhoneJustTalkToThemText(void);
void PhoneThankYouTextScript(void);
void PhoneThankYouText(void);
//#include "data/phone/permanent_numbers.h"
//#include "data/phone/non_trainer_names.h"
//#include "data/phone/phone_contacts.h"
//#include "data/phone/special_calls.h"
