void PokeGear(void);
void PokeGear_InitTilemap(void);
void Pokegear_LoadGFX(void);
//void FastShipGFX(void);
void InitPokegearModeIndicatorArrow(void);
void AnimatePokegearModeIndicatorArrow(void);
void TownMap_GetCurrentLandmark(void);
void TownMap_InitCursorAndPlayerIconPositions(void);
void Pokegear_InitJumptableIndices(void);
void InitPokegearTilemap(void);
void Pokegear_FinishTilemap(void);
void PokegearJumptable(void);
void PokegearClock_Init(void);
void PokegearClock_Joypad(void);
void Pokegear_UpdateClock(void);
void PokegearMap_CheckRegion(void);
void PokegearMap_Init(void);
void PokegearMap_KantoMap(void);
void PokegearMap_JohtoMap(void);
void PokegearMap_ContinueMap(void);
void PokegearMap_InitPlayerIcon(void);
void PokegearMap_InitCursor(void);
void PokegearMap_UpdateLandmarkName(void);
void PokegearMap_UpdateCursorPosition(void);
void TownMap_GetKantoLandmarkLimits(void);
void PokegearRadio_Init(void);
void PokegearRadio_Joypad(void);
void PokegearPhone_Init(void);
void PokegearPhone_Joypad(void);
void PokegearPhone_MakePhoneCall(void);
void PokegearPhone_FinishPhoneCall(void);
void PokegearPhone_GetDPad(void);
void PokegearPhone_UpdateCursor(void);
void PokegearPhone_UpdateDisplayList(void);
void PokegearPhone_DeletePhoneNumber(void);
void PokegearPhoneContactSubmenu(void);
void GetAMPMHours(void);
void Pokegear_SwitchPage(void);
void ExitPokegearRadio_HandleMusic(void);
void DeleteSpriteAnimStruct2ToEnd(void);
void Pokegear_LoadTilemapRLE(void);
void PokegearAskWhoCallText(void);
void PokegearPressButtonText(void);
void PokegearAskDeleteText(void);
void PokegearSpritesGFX(void);
void RadioTilemapRLE(void);
void PhoneTilemapRLE(void);
void ClockTilemapRLE(void);
void v_UpdateRadioStation(void);
void AnimateTuningKnob(void);
void UpdateRadioStation(void);
void LoadPokegearRadioChannelPointer(void);
void RadioChannels(void);
void LoadStation_OaksPokemonTalk(void);
void LoadStation_PokedexShow(void);
void LoadStation_PokemonMusic(void);
void LoadStation_LuckyChannel(void);
void LoadStation_BuenasPassword(void);
void BuenasPasswordName(void);
void NotBuenasPasswordName(void);
void LoadStation_UnownRadio(void);
void LoadStation_PlacesAndPeople(void);
void LoadStation_LetsAllSing(void);
void LoadStation_RocketRadio(void);
void LoadStation_PokeFluteRadio(void);
void LoadStation_EvolutionRadio(void);
void DummyLoadStation(void);
void RadioMusicRestartDE(void);
void RadioMusicRestartPokemonChannel(void);
void Radio_BackUpFarCallParams(void);
void NoRadioStation(void);
void NoRadioMusic(void);
void NoRadioName(void);
void OaksPKMNTalkName(void);
void PokedexShowName(void);
void PokemonMusicName(void);
void LuckyChannelName(void);
void UnownStationName(void);
void PlacesAndPeopleName(void);
void LetsAllSingName(void);
void PokeFluteStationName(void);
void v_TownMap(void);
void PlayRadio(void);
void PlayRadioStationPointers(void);
void LoadStation_PokemonChannel(void);
void PokegearMap(void);
void v_FlyMap(void);
void TownMapBubble(void);
void GetMapCursorCoordinates(void);
void CheckIfVisitedFlypoint(void);
void HasVisitedSpawn(void);
void Pokegear_DummyFunction(void);
void FlyMap(void);
void Pokedex_GetArea(void);
void TownMapBGUpdate(void);
void FillJohtoMap(void);
void FillKantoMap(void);
void FillTownMap(void);
void TownMapPals(void);
void TownMapMon(void);
void TownMapPlayerIcon(void);
void LoadTownMapGFX(void);
void JohtoMap(void);
void KantoMap(void);
void PokedexNestIconGFX(void);
void FlyMapLabelBorderGFX(void);
void EntireFlyMap(void);
//#include "gfx/pokegear/fast_ship.2bpp"
//#include "gfx/pokegear/pokegear_sprites.2bpp.lz"
//#include "gfx/pokegear/radio.tilemap.rle"
//#include "gfx/pokegear/phone.tilemap.rle"
//#include "gfx/pokegear/clock.tilemap.rle"
//#include "data/maps/flypoints.h"
//#include "gfx/pokegear/town_map_palette_map.h"
//#include "gfx/pokegear/johto.bin"
//#include "gfx/pokegear/kanto.bin"
//#include "gfx/pokegear/dexmap_nest_icon.2bpp"
//#include "gfx/pokegear/flymap_label_border.1bpp"
