void DoBattleTransition(void);
void LoadTrainerBattlePokeballTiles(void);
void ConvertTrainerBattlePokeballTilesTo2bpp(void);
void TrainerBattlePokeballTiles(void);
void BattleTransitionJumptable(void);
void StartTrainerBattle_DetermineWhichAnimation(void);
void StartTrainerBattle_Finish(void);
void StartTrainerBattle_NextScene(void);
void StartTrainerBattle_SetUpBGMap(void);
void StartTrainerBattle_Flash(void);
void StartTrainerBattle_SetUpForWavyOutro(void);
void StartTrainerBattle_SineWave(void);
void StartTrainerBattle_SetUpForSpinOutro(void);
void StartTrainerBattle_SpinToBlack(void);
void StartTrainerBattle_SetUpForRandomScatterOutro(void);
void StartTrainerBattle_SpeckleToBlack(void);
void StartTrainerBattle_LoadPokeBallGraphics(void);
void PokeBallTransition(void);
void WipeLYOverrides(void);
void StartTrainerBattle_DrawSineWave(void);
void StartTrainerBattle_ZoomToBlack(void);
void UnusedWaitBGMapOnce(void);
//#include "gfx/overworld/trainer_battle_pokeball_tiles.2bpp"
//#include "gfx/overworld/trainer_battle.pal"
//#include "gfx/overworld/trainer_battle_dark.pal"
